### ISSUE TITLE
work space not building...

### ISSUE THREAD

**Issue by teamemerobocup** [corot/thorp#4]
[error] Unable to download URL [https://raw.github.com/yujinrobot/kobuki-x/hydro-devel/thorp_bringup/thorp_bringup.rosinstall]: HTTP Error 404: Not Found

I am facing this error while writing this command:
yujin_init_workspace -j10 --track=indigo ~/thorp https://raw.github.com/yujinrobot/kobuki-x/hydro-devel/thorp_bringup/thorp_bringup.rosinstall

**Comment by corot** [comment]
Should be fine now. Thanks!
