### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by wangjiwang** [corot/thorp#6]
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "mag_common_cpp_libs" with any of the following names:

    mag_common_cpp_libsConfig.cmake
    mag_common_cpp_libs-config.cmake

  Add the installation prefix of "mag_common_cpp_libs" to CMAKE_PREFIX_PATH
  or set "mag_common_cpp_libs_DIR" to a directory containing one of the above
  files.  If "mag_common_cpp_libs" provides a separate development package or
  SDK, be sure it has been installed.

anyone met this problem?

**Comment by corot** [comment]
Should be fine now. 
May I ask you, what are you using this repo for? As this is mostly a personal project, cannot imagine how can be useful for other people, so I'm curios.

**Comment by wangjiwang** [comment]
> Should be fine now.
> May I ask you, what are you using this repo for? As this is mostly a personal project, cannot imagine how can be useful for other people, so I'm curios.

thanks, I am a graduate and my research topic is ROS, so I want run some demo to do the experience.
