### ISSUE TITLE
simulation

### ISSUE THREAD

**Issue by wangjiwang** [corot/thorp#7]
Excuse me, I don not have any hardware now, and I just need to have turtlebot2 with arm in gazebo to pick something. Is this repositiry can do it?

**Comment by corot** [comment]
Mostly yes, but as I said in your other issue, the code here is mostly a personal project, so I never intended to make something generally usable. But I have indeed a working simulation of a TB2 with an arm in Gazebo.
If you are using melodic, remember that TB2 is not released, so u need the code.
Good luck!
