### ISSUE TITLE
DepthSenseSDK  link is broken.

### ISSUE THREAD

**Issue by wangjiwang** [corot/thorp#8]
-- Using these message generators: gencpp;genlisp;genpy
-- Could NOT find DepthSenseSDK (missing:  DepthSenseSDK_LIBRARY DepthSenseSDK_INCLUDE_DIR) 
CMake Error at thorp/src/softkinetic/softkinetic_camera/CMakeLists.txt:20 (message):
  +++++++++ Could not locate the DepthSense SDK +++++++++

  Please install the SDK before trying to build the 'softkinetic_camera'
  package, see README.txt.
------------------------------------------------------------------------------------------------
Here is the content of the readme:

To use this package in ROS, the DepthSenseSDK for linux needs to be downloaded. 
The download can be found here:
http://www.softkinetic.com/fr-be/support/download.aspx?EntryId=517
To download, you will need to create a free account.

the link is broken.

**Comment by corot** [comment]
Actually, looks like the DepthSenseSDK is gone! Cannot find a replacement driver. Anyway, I don't use  that camera anymore.

I have updated the installation file and instructions to current code and melodic. You can retry, but it's not gonna work, as some required pkgs are not in melodic (turtlebot and object_recognition_ros).

All that said, the code here is mostly a personal project, so I never intended to make something generally usable, but still, probably u can grab interesting code and indeas.
