### ISSUE TITLE
Error in mainpage install instructions?

### ISSUE THREAD

**Issue by reydelsol** [corot/thorp#9]
I tried to execute the following in WSL2 Ubuntu 20.04:
`wstool init src https://raw.githubusercontent.com/corot/thorp/master/thorp_bringup/docker/thorp.rosinstall`

And eventually got this error at the end:
`ERROR in config: Error processing 'thorp' : [thorp] Checkout of https://github.com/corot/thorp.git version master into /home/<user>/thorp/src/thorp failed.
`

So I wonder if there is no longer a "master" in the project to make this work?

**Comment by corot** [comment]
Right!  fixed
